---
  - name: ensure RVM gemset for application
    shell: "source $HOME/.rvm/scripts/rvm ; rvm gemset create {{ app_gemset }}"
    args:
      executable: /bin/bash
    become: yes
    become_user: "{{ app_user_name }}"

  - name: ensure Bundler is in RVM gemset for application
    shell: "source $HOME/.rvm/scripts/rvm ; rvm gemset use {{ app_gemset }} ; gem install bundler"
    args:
      executable: /bin/bash
    become: yes
    become_user: "{{ app_user_name }}"
