---
- name: Set up Ruby on Rails v4 servers
  hosts: rails4-servers
  sudo: True
  roles:
    - ubuntu_common
    - admin_users
    - ubuntu_ssh_server
  vars:
    - default_locale: en_GB.UTF-8
    - system_timezone: Europe/London
    - custom_ssh_port: 54321
