---
- name: Set up Ubuntu servers
  hosts: all
  sudo: True
  roles:
    - admin_users
    - ubuntu_common
    - ubuntu_ssh_server
  vars:
    - default_locale: en_GB.UTF-8
    - system_timezone: Europe/London
    - custom_ssh_port: 53124
