---
- name: Set up Backup
  hosts: all
  roles:
    - backup_app_deps
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ["ruby-2.4.2"],
        rvm1_user: "{{ app_user_name }}",
        rvm1_install_flags: "--auto-dotfiles --user-install",
        rvm1_ruby_install_flags: "--autolibs=disable"
      }
  vars:
    - app_user_name: backupapp
    - app_user_full_name: "Backup application"
    - app_user_id: 1002
