---
- name: Set up Ruby on Rails v4 servers
  hosts: rails4-servers
  sudo: True
  roles:
    - single_sysadmin
    - ubuntu_common
    - ubuntu_ssh_server
    - ubuntu_mysql_server
    - rails4_server
    - ubuntu_monit
  vars:
    - default_locale: en_GB.UTF-8
    - system_timezone: Europe/London
    - custom_ssh_port: 54321
    - user_name: deploy
    - user_full_name: "Deployment account"
    - user_id: 1001
    - user_password_sha512: "CHANGEME"
    - monit_email_recipient: "CHANGEME@DOMAIN.EXAMPLE"
    - monit_email_sender: "CHANGEME@DOMAIN.EXAMPLE"
    - monit_email_sender_password: "CHANGEME"
    - monit_email_sender_host: "smtp.gmail.com"
    - monit_email_sender_port: 587
    - monit_password: "CHANGEME"
    - mysql_root_db_password: "{{ mysql_root_pass }}"
