---
- name: Set up Ruby on Rails v4 application
  hosts: rails4-servers
  sudo: True
  sudo_user: "{{ app_user_name }}"
  roles:
    - role: rvm_io.rvm1-ruby
      rvm1_install_flags: "--auto-dotfiles --user-install"
      rvm1_install_path: "/home/{{ app_user_name }}/.rvm"
      rvm1_rvm_version: "stable"
      rvm1_user: "{{ app_user_name }}"
      rvm1_rubies:
        - "{{ app_ruby_version }}"
    - rails4_app
  vars:
    - default_locale: en_GB.UTF-8
    - system_timezone: Europe/London
    - custom_ssh_port: 53124
    - app_name: "dummy_app_rails"
    - app_hostname: "dummyapp.example"
    - app_environment: "production"
    - app_user_name: "deploy"
    - app_db_username: "dummy_app_prd"
    - app_db_password: "CHANGEME"
    - app_db_name: "dummy_app_prd"
    - app_ruby_version: "ruby-2.2.2"
    - app_gemset: "myapp_prd"
    - app_workers: 3
