---
- name: Ubuntu servers
  hosts: all
  sudo: True
  roles:
    - ubuntu_common
    - admin_users
    - ubuntu_ssh_server
  vars:
    - default_locale: en_GB.UTF-8
    - system_timezone: Europe/London
