---
- name: Set up Ubuntu servers
  hosts: all
  roles:
    - single_sysadmin
    - ubuntu_common
    - ubuntu_ssh_server
  vars:
    - default_locale: en_GB.UTF-8
    - system_timezone: Europe/London
    - custom_ssh_port: 53124
    - user_name: deploy
    - user_full_name: "Deployment account"
    - user_id: 1001
  vars_prompt:
    - name: "machine_hostname"
      prompt: "New full hostname"
      private: no
    - name: "user_password_sha512"
      prompt: "Password for UNIX user account"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 8
