---
- name: Set up Ruby on Rails v4 application
  hosts: rails4-servers
  roles:
    - role: rvm_io.rvm1-ruby
      sudo: yes
      rvm1_install_flags: "--auto-dotfiles --user-install"
      rvm1_install_path: "/home/{{ app_user_name }}/.rvm"
      rvm1_rvm_version: "stable"
      rvm1_user: "{{ app_user_name }}"
      rvm1_rubies:
        - "{{ app_ruby_version }}"
    - rails4_app
    - rails4_app_db
  vars:
    - app_name: "dummy_app_rails"
    - app_hostname: "dummyapp.example"
    - app_environment: "production"
    - app_user_name: "deploy"
    - app_db_username: "dummy_app_prd"
    - app_db_name: "dummy_app_prd"
    - app_ruby_version: "ruby-2.2.3"
    - app_gemset: "myapp_prd"
  vars_prompt:
    - name: "app_db_password"
      prompt: "MySQL account password for application"
      private: yes
      confirm: yes
    - name: "app_workers"
      prompt: "No. of delayed_job workers (0 for none)"
