---
- name: Set up Ruby on Rails v4 servers
  hosts: rails4-servers
  roles:
    - single_sysadmin
    - ubuntu_common
    - ubuntu_ssh_server
    - ubuntu_mysql_client
    - ubuntu_mysql_server
    - rails4_server
    - ubuntu_monit
    - ubuntu_firewall
  vars:
    - default_locale: en_GB.UTF-8
    - system_timezone: Europe/London
    - custom_ssh_port: 53124
    - user_name: deploy
    - user_full_name: "Deployment account"
    - user_id: 1001
    - monit_email_recipient: "CHANGEME@DOMAIN.EXAMPLE"
    - monit_email_sender: "CHANGEME@DOMAIN.EXAMPLE"
    - monit_email_sender_host: "smtp.gmail.com"
    - monit_email_sender_port: 587
    - mysql_version: "5.6"
  vars_prompt:
    - name: "hostname"
      prompt: "New full hostname"
    - name: "monit_password"
      prompt: "Password for Monit access"
      private: yes
      confirm: yes
    - name: "monit_email_sender_password"
      prompt: "Email password for Monit messages"
      private: yes
      confirm: yes
    - name: "mysql_root_db_password"
      prompt: "Password for MySQL root"
      private: yes
      confirm: yes
    - name: "user_password_sha512"
      prompt: "Password for UNIX user account"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 8
