---
  - name: ensure prerequisites for Phusion APT repository
    apt: name={{ item }} state=present
    with_items:
      - apt-transport-https
      - ca-certificates
  - name: ensure key for Phusion APT repository
    apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7 state=present
  - name: ensure APT repository for Phusion Passenger
    apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main' state=present
  - name: ensure Phusion Passenger
    apt: name={{ item }} state=present
    with_items:
      - nginx-extras
      - passenger
