---
  - name: ensure SSH package is present
    apt: name=openssh-server state=present
    become: yes

  - name: ensure SSH service is enabled and running
    service: name=ssh state=started enabled=yes
    become: yes
