---
  - name: copy .my.cnf file to Ansible account with root password credentials
    template: src=client/my.cnf.j2 dest=/home/{{ ansible_ssh_user }}/.my.cnf owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0600
  - name: copy .my.cnf file to root account with root password credentials
    template: src=client/my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  - name: set MySQL root password
    mysql_user: user=root host="{{ item }}" password="{{ mysql_root_db_password }}"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
