---
  - name: ensure MySQL app database
    mysql_db: name={{ app_db_name }} collation=utf8_general_ci encoding=utf8 state=present
  - name: ensure MySQL app user account
    mysql_user: name={{ app_db_username }} password={{ app_db_password }} priv={{ app_db_name }}.*:CREATE,DROP,ALTER,INDEX,SELECT,INSERT,UPDATE,DELETE state=present
