---
  - name: test for presence of Monit
    stat: path=/usr/bin/monit
    register: monit_exe

  - name: set value of has_monit
    set_fact: has_monit=True
    when: monit_exe.stat.isreg is defined and monit_exe.stat.isreg
