---
  - name: ensure nginx virtual host for Rails application
    template: src=nginx_vhost.j2 dest=/etc/nginx/sites-available/{{ app_name }} owner=root group=root mode=0644
    notify: reload nginx
  - name: enable nginx virtual host for Rails application
    file: src=/etc/nginx/sites-available/{{ app_name }} dest=/etc/nginx/sites-enabled/{{ app_name }} owner=root group=root state=link force=yes
    notify: reload nginx
