---
  - name: ensure Memcache nodes for Elasticache
    elasticache:
      name: "{{ app_name }}-{{ env_name }}-mc"
      state: present
      engine: memcached
      cache_engine_version: 1.4.24
      aws_region: "{{ aws_region }}"
      zone: "{{ aws_region }}a"
      cache_subnet_group: "nets-{{ app_name }}-{{ env_name }}-cache"
      security_group_ids: "{{ security_group_cache.group_id }}"
      node_type: cache.t2.micro
      num_nodes: "{{ memcached_nodes }}"
      cache_port: 11211
    when: memcached_nodes|int > 0
