---
  - include: vpc.yml
  - include: subnet_rds.yml
  - include: subnet_elasticache.yml
  - include: secgroup_lb.yml
  - include: secgroup_app.yml
  - include: secgroup_db.yml
  - include: secgroup_cache.yml
  - include: rds_mysql.yml
  - include: elasticache_memcache.yml
