---
  - name: ensure user account for Backup
    user: 
      name: "{{ app_user_name }}"
      comment: "{{ app_user_full_name }}"
      groups: backupadmins
      shell: /bin/bash
      uid: "{{ app_user_id }}"
      state: present
    become: yes