---
  - name: refresh Apt package index
    apt: update-cache=yes cache_valid_time=86400
    become: yes

  - name: ensure Debian configuration utilities
    apt: name=debconf-utils state=present
    become: yes
